export enum ESessionErrorCodes {
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = `USER_NOT_FOUND`,
  PASSWORD_IS_INVALID = `PASSWORD_IS_INVALID`,
  CANT_CREATE_SESSION = `CANT_CREATE_SESSION`,
  SESSION_NOT_FOUND = `SESSION_NOT_FOUND`,
  TOKEN_NOT_FOUND = `TOKEN_NOT_FOUND`,
  CANT_SET_SESSION_DATA = 'CANT_SET_SESSION_DATA',
  CANT_REMOVE_SESSION = 'CANT_REMOVE_SESSION',
  REPEAT_LOGIN = 'REPEAT_LOGIN',
}

export enum ESessionApiDescription {
  REPEAT_LOGIN = 'Выполните вход в систему повторно',
}
